import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, collection, doc, setDoc, getDocs, deleteDoc, onSnapshot } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const firebaseConfig = {
  apiKey: "AIzaSyCLaqaOCJnkfG4LID1Y5RoFpgEsX9nYGOM",
  authDomain: "testeapi-1ad07.firebaseapp.com",
  databaseURL: "https://testeapi-1ad07-default-rtdb.firebaseio.com",
  projectId: "testeapi-1ad07",
  storageBucket: "testeapi-1ad07.firebasestorage.app",
  messagingSenderId: "323295128076",
  appId: "1:323295128076:web:3af167424f75b680f19c29"
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);
document.getElementById("statusNuvem").innerHTML = "✅ Nuvem testeapi-1ad07 conectada - correcao Paulo Loz OK";
document.getElementById("infoNuvem").innerHTML = "☁️ Nuvem ATIVA testeapi-1ad07 - resultados em avaliacoes";

const CHAVE_USUARIOS = "sistemaProvasUsuarios", CHAVE_PROVAS = "sistemaProvas", CHAVE_RESULTADOS = "sistemaResultados";
window.usuarios = JSON.parse(localStorage.getItem(CHAVE_USUARIOS) || "[]");
window.provas = JSON.parse(localStorage.getItem(CHAVE_PROVAS) || "[]");
window.resultados = JSON.parse(localStorage.getItem(CHAVE_RESULTADOS) || "[]");
window.alunos = JSON.parse(localStorage.getItem("sistemaProvasAlunos") || "[]");
usuarios.forEach(u => { if (u.bloqueado === undefined) u.bloqueado = false }); alunos.forEach(a => { if (a.bloqueado === undefined) a.bloqueado = false });
if (!usuarios.some(u => u.tipo === "master")) { usuarios.push({ id: "master-1", nome: "Administrador Master", usuario: "master", senha: "1234", tipo: "master", bloqueado: false }); localStorage.setItem(CHAVE_USUARIOS, JSON.stringify(usuarios)) }
provas.forEach(p => { if (!p.questoes) p.questoes = []; if (!p.seguranca) p.seguranca = segurancaPadrao(); if (!p.maxTentativas) p.maxTentativas = 1 });

async function salvarNuvem(tipo, id, dados) { try { await setDoc(doc(db, tipo, String(id)), dados); } catch (e) { console.log(e) } }
async function deletarNuvem(tipo, id) { try { await deleteDoc(doc(db, tipo, String(id))); } catch (e) { } }

async function carregarNuvem() {
  try {
    const [aSnap, pSnap, rSnap, profSnap] = await Promise.all([
      getDocs(collection(db, "alunos")),
      getDocs(collection(db, "provas")),
      getDocs(collection(db, "avaliacoes")),
      getDocs(collection(db, "professores"))
    ]);
    if (!aSnap.empty) { alunos = aSnap.docs.map(d => d.data()); localStorage.setItem("sistemaProvasAlunos", JSON.stringify(alunos)); }
    if (!pSnap.empty) { provas = pSnap.docs.map(d => d.data()); localStorage.setItem(CHAVE_PROVAS, JSON.stringify(provas)); }
    if (!rSnap.empty) { resultados = rSnap.docs.map(d => d.data()); localStorage.setItem(CHAVE_RESULTADOS, JSON.stringify(resultados)); }
    if (!profSnap.empty) { const profs = profSnap.docs.map(d => d.data()); usuarios = [...usuarios.filter(u => u.tipo === "master"),...profs.map(p => ({...p, tipo: "professor" }))]; localStorage.setItem(CHAVE_USUARIOS, JSON.stringify(usuarios)); }
    document.getElementById("statusNuvem").innerHTML = "✅ Sincronizado: " + alunos.length + " alunos, " + provas.length + " provas, " + resultados.length + " avaliações";
  } catch (e) { console.log(e); }
  try {
    onSnapshot(collection(db, "avaliacoes"), (snap) => { resultados = snap.docs.map(d => d.data()); localStorage.setItem(CHAVE_RESULTADOS, JSON.stringify(resultados)); if (window.usuarioLogado) listarResultados(); });
    onSnapshot(collection(db, "alunos"), (snap) => { alunos = snap.docs.map(d => d.data()); localStorage.setItem("sistemaProvasAlunos", JSON.stringify(alunos)); });
    onSnapshot(collection(db, "provas"), (snap) => { provas = snap.docs.map(d => d.data()); localStorage.setItem(CHAVE_PROVAS, JSON.stringify(provas)); if (window.usuarioLogado) { listarProvas(); atualizarSelect(); } });
    onSnapshot(collection(db, "professores"), (snap) => { const profs = snap.docs.map(d => d.data()); usuarios = [...usuarios.filter(u => u.tipo === "master"),...profs.map(p => ({...p, tipo: "professor" }))]; localStorage.setItem(CHAVE_USUARIOS, JSON.stringify(usuarios)); });
  } catch (e) { }
}
carregarNuvem();
window.salvarNuvem = salvarNuvem; window.deletarNuvem = deletarNuvem;
window.salvarAlunos = function () { localStorage.setItem("sistemaProvasAlunos", JSON.stringify(alunos)) }
window.salvarUsuarios = function () { localStorage.setItem(CHAVE_USUARIOS, JSON.stringify(usuarios)) }
window.salvar = function () { localStorage.setItem(CHAVE_PROVAS, JSON.stringify(provas)); localStorage.setItem(CHAVE_RESULTADOS, JSON.stringify(resultados)); localStorage.setItem(CHAVE_USUARIOS, JSON.stringify(usuarios)); localStorage.setItem("sistemaProvasAlunos", JSON.stringify(alunos)); }
window.escapeHTML = function (t) { return String(t?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#039;") }
window.mostrar = function (id) { ["inicio", "aluno", "cadastroAluno", "fazerProva", "resultado", "login", "professor"].forEach(t => document.getElementById(t)?.classList.add("hidden")); document.getElementById(id)?.classList.remove("hidden") }
window.abrirLogin = function () { mostrar("login") }
window.login = function () { const u = document.getElementById("usuarioLogin").value.trim().toLowerCase(), s = document.getElementById("senhaLogin").value; const e = usuarios.find(x => x.usuario.toLowerCase() === u && x.senha === s); if (!e) { document.getElementById("erroLogin").textContent = "❌ Usuário ou senha incorretos"; return } if (e.bloqueado) { document.getElementById("erroLogin").textContent = "🔒 BLOQUEADO pelo Master"; return } window.usuarioLogado = e; abrirPainel() }

// CORRIGIDO - Agora mostra botao Banco
window.abrirPainel = function () { mostrar("professor"); atualizarUsuarioLogado(); document.getElementById("botaoMaster").classList.toggle("hidden", usuarioLogado.tipo!== "master"); document.getElementById("botaoAlunosMaster").classList.toggle("hidden", usuarioLogado.tipo!== "master"); document.getElementById("botaoBancoMaster").classList.toggle("hidden", usuarioLogado.tipo!== "master"); painelProfessor("provas") }

window.atualizarUsuarioLogado = function () { const d = document.getElementById("usuarioLogado"); if (!usuarioLogado) { d.innerHTML = ""; return } const b = usuarioLogado.tipo === "master"? '<span class="badge-master">MASTER</span>' : '<span class="badge-professor">PROFESSOR</span>'; d.innerHTML = `👤 <strong>${escapeHTML(usuarioLogado.nome)}</strong> ${b}` }
window.sair = function () { clearInterval(timer); usuarioLogado = null; mostrar("inicio") }
window.painelProfessor = function (t) { ["painelProvas", "painelQuestoes", "painelResultados", "painelSenha", "painelProfessores", "painelAlunos", "painelBanco"].forEach(x => document.getElementById(x)?.classList.add("hidden")); if (t === "provas") { document.getElementById("painelProvas").classList.remove("hidden"); listarProvas() } if (t === "questoes") { document.getElementById("painelQuestoes").classList.remove("hidden"); atualizarSelect(); listarQuestoes() } if (t === "resultados") { document.getElementById("painelResultados").classList.remove("hidden"); listarResultados() } if (t === "senha") { document.getElementById("painelSenha").classList.remove("hidden") } if (t === "professores") { if (usuarioLogado?.tipo!== "master") return; document.getElementById("painelProfessores").classList.remove("hidden"); listarProfessores() } if (t === "alunos") { if (usuarioLogado?.tipo!== "master") return; document.getElementById("painelAlunos").classList.remove("hidden"); listarAlunosMaster() } if (t === "banco") { if (usuarioLogado?.tipo!== "master") return; document.getElementById("painelBanco").classList.remove("hidden"); } }
window.abrirCadastroAluno = function () { document.getElementById("erroCadastroAluno").style.display = "none"; document.getElementById("erroCadastroAluno").textContent = ""; mostrar("cadastroAluno") }
window.mostrarErroCadastro = function (msg) { const e = document.getElementById("erroCadastroAluno"); e.textContent = "❌ " + msg; e.style.display = "block"; }
window.cadastrarAluno = async function () {
  const n = document.getElementById("cadAlunoNome").value.trim();
  const u = document.getElementById("cadAlunoUsuario").value.trim().toLowerCase().replace(/\s+/g, "");
  const s = document.getElementById("cadAlunoSenha").value;
  const s2 = document.getElementById("cadAlunoSenha2").value;
  const e = document.getElementById("erroCadastroAluno");
  e.style.display = "none"; e.textContent = "";
  if (!n || n.length < 3) return mostrarErroCadastro("Digite seu nome completo (ex: Paulo Loz)");
  if (n.split(" ").length < 2) return mostrarErroCadastro("Digite nome e sobrenome");
  if (!u || u.length < 3) return mostrarErroCadastro("Usuário deve ter no mínimo 3 letras, sem espaço (ex: paulo)");
  if (s.length < 4) return mostrarErroCadastro("Senha deve ter no mínimo 4 caracteres");
  if (s!== s2) return mostrarErroCadastro("As senhas não conferem");
  if (alunos.some(a => a.usuario.toLowerCase() === u)) return mostrarErroCadastro("Este usuário '" + u + "' já existe como aluno");
  if (usuarios.some(us => us.usuario.toLowerCase() === u)) return mostrarErroCadastro("Este usuário '" + u + "' já existe como professor/master. Escolha outro");
  const novo = { id: "aluno-" + Date.now(), nome: n, usuario: u, senha: s, bloqueado: false, dataCadastro: new Date().toLocaleString("pt-BR") };
  alunos.push(novo); salvarAlunos(); salvar(); await salvarNuvem("alunos", novo.id, novo);
  alert("✅ Cadastro criado! Nome: " + n + " Usuário: " + u);
  document.getElementById("cadAlunoNome").value = ""; document.getElementById("cadAlunoUsuario").value = ""; document.getElementById("cadAlunoSenha").value = ""; document.getElementById("cadAlunoSenha2").value = ""; mostrar("aluno");
}
window.usuarioLogado = null; window.aluno = { nome: "", usuario: "" }; window.provaAtual = null; window.timer = null; window.segundos = 0; window.editando = null; window.editandoProva = null; window.imagemAtual = null; window.provaEnviada = false;
window.sessaoSegura = { ativa: false, ocorrencias: [], bloqueada: false, avisando: false, ultimaVisibilidade: 0, emCarencia: false };
window.loginAluno = function () {
  const nome = document.getElementById("loginAlunoNome").value.trim(), senha = document.getElementById("loginAlunoSenha").value;
  const a = alunos.find(x => x.nome.toLowerCase() === nome.toLowerCase() && x.senha === senha);
  if (!a) { document.getElementById("erroLoginAluno").textContent = "❌ Nome ou senha incorretos"; return }
  if (a.bloqueado) { document.getElementById("erroLoginAluno").textContent = "🔒 Aluno BLOQUEADO pelo Master"; return }
  document.getElementById("erroLoginAluno").textContent = ""; aluno = { id: a.id, nome: a.nome, usuario: a.usuario };
  const cod = prompt("Código da avaliação:"); if (!cod) return;
  const p = provas.find(x => x.codigo === cod.trim().toUpperCase()); if (!p) return alert("Código inválido"); if (!p.liberada) return alert("Não liberada");
  const agora = new Date(); if (p.dataInicio && agora < new Date(p.dataInicio)) return alert("Ainda não começou"); if (p.dataFim && agora > new Date(p.dataFim)) return alert("Período terminou");
  const maxT = p.maxTentativas || 1, feitas = resultados.filter(r => r.usuario === a.usuario && r.provaId === p.id).length;
  if (feitas >= maxT) return alert("🚫 Limite de " + maxT + " atingido"); if (feitas > 0 &&!confirm("Já fez " + feitas + " vez(es). Restam " + (maxT - feitas) + ". Substituir?")) return;
  iniciarProva(p.id)
}
window.iniciarProva = function (id) { provaAtual = provas.find(p => p.id === id); if (!provaAtual ||!provaAtual.questoes.length) return alert("Sem questões"); provaAtual.seguranca = Object.assign(segurancaPadrao(), provaAtual.seguranca || {}); mostrar("fazerProva"); document.getElementById("tituloProva").textContent = provaAtual.nome; document.getElementById("dadosAluno").textContent = aluno.nome + " - Tentativa " + (resultados.filter(r => r.usuario === aluno.usuario && r.provaId === provaAtual.id).length + 1) + "/" + (provaAtual.maxTentativas || 1); provaEnviada = false; sessaoSegura = { ativa: false, ocorrencias: [], bloqueada: false, avisando: false, ultimaVisibilidade: 0, emCarencia: true }; montarProva(); document.getElementById("statusSeguranca").innerHTML = `<div class="security-status" style="background:#fef3c7;border-color:#fbbf24;color:#92400e">⏳ Entrando... segurança ativa em 2s</div>`; iniciarTimer(calcularTempoDisponivel()); setTimeout(() => { sessaoSegura.ativa =!!provaAtual.seguranca.ativo; sessaoSegura.emCarencia = false; sessaoSegura.ultimaVisibilidade = Date.now() + 1000; atualizarStatusSeguranca(); if (sessaoSegura.ativa) ativarModoSeguro(); }, 2500); }
window.calcularTempoDisponivel = function () { let s = Number(provaAtual.tempo) * 60; if (provaAtual.dataFim) { const r = Math.floor((new Date(provaAtual.dataFim) - new Date()) / 1000); if (r < s) s = Math.max(0, r); } return Math.ceil(s / 60) }
window.embaralharAlternativas = function (a) { const r = [...a]; for (let i = r.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1));[r[i], r[j]] = [r[j], r[i]] } return r }
window.montarProva = function () { const d = document.getElementById("questoesAluno"); d.innerHTML = ""; provaAtual.questoes.forEach((q, i) => { let h = `<div class="questao"><h3>Q${i + 1}: ${escapeHTML(q.enunciado)}</h3>`; if (q.imagem) h += `<div style="text-align:center;margin:12px 0"><img src="${q.imagem}" style="width:${q.imagemLargura || 500}px;max-width:100%;border:1px solid #ddd;border-radius:8px"></div>`; const alts = embaralharAlternativas(q.opcoes.map((t, idx) => ({ t, idx }))); alts.forEach((alt, j) => { const letra = String.fromCharCode(65 + j); h += `<div class="alternativa" onclick="this.querySelector('input').checked=true"><label><input type="radio" name="questao${i}" value="${alt.idx}"><span><strong>${letra})</strong> ${escapeHTML(alt.t)}</span></label></div>`; }); h += "</div>"; d.innerHTML += h; }); }
window.iniciarTimer = function (min) { clearInterval(timer); segundos = Math.max(0, Math.floor(min * 60)); atualizarTimer(); timer = setInterval(() => { segundos--; atualizarTimer(); if (segundos <= 0) { clearInterval(timer); alert("Tempo encerrado"); finalizarProva(true) } }, 1000) }
window.atualizarTimer = function () { document.getElementById("cronometro").textContent = String(Math.floor(segundos / 60)).padStart(2, "0") + ":" + String(segundos % 60).padStart(2, "0") }
window.atualizarStatusSeguranca = function () { const d = document.getElementById("statusSeguranca"); if (!sessaoSegura.ativa) { if (sessaoSegura.emCarencia) { d.innerHTML = `<div class="security-status" style="background:#fef3c7;border-color:#fbbf24;color:#92400e">⏳ Iniciando... segurança ativa em instantes</div>`; document.body.classList.remove("exam-secure"); return } d.innerHTML = ""; document.body.classList.remove("exam-secure"); return } d.innerHTML = `<div class="security-status">🔒 Protegida — Ocorrências: ${sessaoSegura.ocorrencias.length}/${provaAtual.seguranca.maxOcorrencias}</div>` }
window.ativarModoSeguro = function () { document.body.classList.add("exam-secure"); criarWatermark(); if (provaAtual.seguranca.fullscreen) solicitarFullscreen() }
window.criarWatermark = function () { const w = document.getElementById("watermark"); w.innerHTML = ""; w.style.display = "block"; const txt = `${aluno.nome} • ${aluno.usuario}`; for (let i = 0; i < 30; i++) { const s = document.createElement("span"); s.textContent = txt; s.style.left = (i % 5 * 25 - 10) + "%"; s.style.top = (Math.floor(i / 5) * 18 - 5) + "%"; w.appendChild(s) } }
window.removerProtecaoVisual = function () { document.body.classList.remove("exam-secure"); document.getElementById("watermark").style.display = "none" }
window.solicitarFullscreen = async function () { try { if (!document.fullscreenElement && document.documentElement.requestFullscreen) await document.documentElement.requestFullscreen() } catch (e) { } }
window.sairFullscreenSeguro = function () { if (document.fullscreenElement && document.exitFullscreen) document.exitFullscreen().catch(() => { }) }
window.registrarOcorrencia = function (t, d) { if (sessaoSegura.emCarencia) return; if (!sessaoSegura.ativa || sessaoSegura.bloqueada || provaEnviada) return; const a = Date.now(); if (a - sessaoSegura.ultimaVisibilidade < 700) return; sessaoSegura.ultimaVisibilidade = a; sessaoSegura.ocorrencias.push({ tipo: t, detalhe: d || "", data: new Date().toLocaleString("pt-BR") }); atualizarStatusSeguranca(); mostrarAviso({ tipo: t, detalhe: d }); if (sessaoSegura.ocorrencias.length >= provaAtual.seguranca.maxOcorrencias && provaAtual.seguranca.acaoLimite!== "registrar") { sessaoSegura.bloqueada = true; setTimeout(() => encerrarPorSeguranca(), 900) } }
window.mostrarAviso = function (r) { if (sessaoSegura.avisando) return; sessaoSegura.avisando = true; document.getElementById("warningText").textContent = "Ocorrência: " + r.tipo + (r.detalhe? " — " + r.detalhe : ""); document.getElementById("warningCount").textContent = sessaoSegura.ocorrencias.length + "/" + provaAtual.seguranca.maxOcorrencias; document.getElementById("warningOverlay").style.display = "flex" }
window.fecharAviso = function () { document.getElementById("warningOverlay").style.display = "none"; sessaoSegura.avisando = false; if (sessaoSegura.ativa && provaAtual.seguranca.fullscreen &&!document.fullscreenElement) solicitarFullscreen() }
window.encerrarPorSeguranca = function () { document.getElementById("warningOverlay").style.display = "none"; document.getElementById("lockText").textContent = `Limite de ${provaAtual.seguranca.maxOcorrencias} atingido`; document.getElementById("lockOverlay").style.display = "flex"; setTimeout(() => finalizarProva(true, true), 700) }
document.addEventListener("visibilitychange", () => { if (sessaoSegura.emCarencia) return; if (sessaoSegura.ativa &&!provaEnviada && document.hidden && provaAtual.seguranca.saida) registrarOcorrencia("Saída", "Aba em segundo plano") });
window.addEventListener("blur", () => { if (sessaoSegura.emCarencia) return; if (sessaoSegura.ativa &&!provaEnviada && provaAtual.seguranca.saida &&!document.hidden) registrarOcorrencia("Perda de foco", "Janela perdeu foco") });
document.addEventListener("fullscreenchange", () => { if (sessaoSegura.emCarencia) return; if (sessaoSegura.ativa &&!provaEnviada && provaAtual.seguranca.fullscreen &&!document.fullscreenElement) { registrarOcorrencia("Saída tela cheia", "Saiu do fullscreen"); setTimeout(() => { if (!provaEnviada &&!sessaoSegura.bloqueada) solicitarFullscreen() }, 500) } });
document.addEventListener("contextmenu", e => { if (sessaoSegura.emCarencia) return; if (sessaoSegura.ativa && provaAtual.seguranca.contexto) { e.preventDefault(); registrarOcorrencia("Botão direito", "Menu bloqueado") } });
document.addEventListener("copy", e => { if (sessaoSegura.emCarencia) return; if (sessaoSegura.ativa && provaAtual.seguranca.copia) { e.preventDefault(); registrarOcorrencia("Cópia", "Tentativa") } });
document.addEventListener("keydown", e => { if (sessaoSegura.emCarencia) return; if (!sessaoSegura.ativa || provaEnviada) return; const s = provaAtual.seguranca, k = e.key.toLowerCase(), c = e.ctrlKey || e.metaKey; if (s.printScreen && (e.key === "PrintScreen")) { e.preventDefault(); registrarOcorrencia("Print Screen", ""); return } if (s.impressao && c && k === "p") { e.preventDefault(); registrarOcorrencia("Impressão", "Ctrl+P"); return } if (s.copia && c && ["c", "x", "v"].includes(k)) { e.preventDefault(); registrarOcorrencia("Copiar/colar", ""); return } if (s.atalhos && (e.key === "F12" || (c && e.shiftKey && ["i", "j", "c"].includes(k)) || (c && ["s", "u"].includes(k)))) { e.preventDefault(); registrarOcorrencia("Atalho navegador", ""); return } });
window.finalizarProva = async function (f = false, pS = false) {
  if (!provaAtual || provaEnviada) return; if (!f && segundos > 0 &&!confirm("Finalizar?")) return; provaEnviada = true; clearInterval(timer);
  let ac = 0; provaAtual.questoes.forEach((q, i) => { const r = document.querySelector(`input[name="questao${i}"]:checked`); if (r && Number(r.value) === q.correta) ac++ });
  const tot = provaAtual.questoes.length, nota = tot? (ac / tot) * 10 : 0;
  const res = { id: Date.now(), aluno: aluno.nome, usuario: aluno.usuario, alunoId: aluno.id, prova: provaAtual.nome, provaId: provaAtual.id, professorId: provaAtual.professorId, codigo: provaAtual.codigo, acertos: ac, total: tot, nota: Number(nota.toFixed(1)), data: new Date().toLocaleString("pt-BR"), tentativas: (resultados.filter(r => r.usuario === aluno.usuario && r.provaId === provaAtual.id).length + 1), seguranca: { ativa: sessaoSegura.ativa, ocorrencias: sessaoSegura.ocorrencias, status: pS? "ENCERRADA_POR_SEGURANCA" : (f && segundos <= 0? "TEMPO_ESGOTADO" : "FINALIZADA") } };
  const idx = resultados.findIndex(r => r.usuario === aluno.usuario && r.provaId === provaAtual.id); if (idx >= 0) resultados[idx] = res; else resultados.push(res); salvar(); await salvarNuvem("avaliacoes", res.id, res);
  removerProtecaoVisual(); sairFullscreenSeguro(); document.getElementById("lockOverlay").style.display = "none";
  const min = Number(provaAtual.notaMinima?? 6); mostrar("resultado");
  document.getElementById("resultadoConteudo").innerHTML = `<p style="text-align:center"><strong>${escapeHTML(aluno.nome)}</strong></p><div class="nota">${res.nota.toFixed(1)}</div><h2 style="text-align:center;color:${res.nota >= min? "#16a34a" : "#dc2626"}">${res.nota >= min? "APROVADO" : "ABAIXO"}</h2><p style="text-align:center">${ac} de ${tot}</p><p style="text-align:center;color:#2563eb;font-size:12px">☁️ Nota enviada para nuvem testeapi-1ad07</p>`;
  provaAtual = null; sessaoSegura = { ativa: false, ocorrencias: [], bloqueada: false, avisando: false, emCarencia: false }
}
window.segurancaPadrao = function () { return { ativo: false, fullscreen: true, saida: true, impressao: true, atalhos: true, copia: true, contexto: true, printScreen: true, selecao: true, maxOcorrencias: 3, acaoLimite: "encerrar" } }
window.lerSeguranca = function () { const s = segurancaPadrao(); s.ativo = document.getElementById("segAtivo").checked; s.fullscreen = document.getElementById("segFullscreen").checked; s.saida = document.getElementById("segSaida").checked; s.impressao = document.getElementById("segImpressao").checked; s.atalhos = document.getElementById("segAtalhos").checked; s.copia = document.getElementById("segCopia").checked; s.contexto = document.getElementById("segContexto").checked; s.printScreen = document.getElementById("segPrintScreen").checked; s.selecao = document.getElementById("segSelecao").checked; s.maxOcorrencias = Math.max(1, Number(document.getElementById("segMax").value) || 3); s.acaoLimite = document.getElementById("segAcao").value; return s }
window.aplicarSegurancaForm = function (s) { s = Object.assign(segurancaPadrao(), s || {}); document.getElementById("segAtivo").checked =!!s.ativo; document.getElementById("segFullscreen").checked = s.fullscreen!== false; document.getElementById("segSaida").checked = s.saida!== false; document.getElementById("segImpressao").checked = s.impressao!== false; document.getElementById("segAtalhos").checked = s.atalhos!== false; document.getElementById("segCopia").checked = s.copia!== false; document.getElementById("segContexto").checked = s.contexto!== false; document.getElementById("segPrintScreen").checked = s.printScreen!== false; document.getElementById("segSelecao").checked = s.selecao!== false; document.getElementById("segMax").value = s.maxOcorrencias || 3; document.getElementById("segAcao").value = s.acaoLimite || "encerrar"; document.getElementById("segOpcoes").classList.toggle("hidden",!s.ativo) }
document.getElementById("segAtivo").addEventListener("change", e => document.getElementById("segOpcoes").classList.toggle("hidden",!e.target.checked));
window.gerarCodigo = function () { const c = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; let x = ""; for (let i = 0; i < 6; i++)x += c[Math.floor(Math.random() * c.length)]; return x }
window.codigoUnico = function () { let c; do { c = gerarCodigo() } while (provas.some(p => p.codigo === c)); return c }
window.criarProva = async function () { if (!usuarioLogado) return; const nome = document.getElementById("nomeProva").value.trim(), desc = document.getElementById("descricaoProva").value.trim(); const tempo = Number(document.getElementById("tempo").value), notaMin = Number(document.getElementById("notaMinima").value), maxT = Math.max(1, Math.min(10, Number(document.getElementById("maxTentativas").value) || 1)); const di = document.getElementById("dataInicio").value, df = document.getElementById("dataFim").value; if (!nome || tempo <= 0) return alert("Informe nome e tempo"); if (di && df && new Date(df) <= new Date(di)) return alert("Data final posterior"); const seg = lerSeguranca(); if (editandoProva!== null) { const p = provas.find(x => x.id === editandoProva); if (!p) return; p.nome = nome; p.descricao = desc; p.tempo = tempo; p.notaMinima = notaMin; p.maxTentativas = maxT; p.dataInicio = di; p.dataFim = df; p.seguranca = seg; salvar(); await salvarNuvem("provas", p.id, p); alert("✅ Atualizada na nuvem") } else { const p = { id: Date.now(), professorId: usuarioLogado.id, nome, descricao: desc, tempo, notaMinima: notaMin, maxTentativas: maxT, dataInicio: di, dataFim: df, codigo: codigoUnico(), liberada: false, gabarito: false, questoes: [], seguranca: seg }; provas.push(p); salvar(); await salvarNuvem("provas", p.id, p); alert("✅ Criada! Código: " + p.codigo) } limparProva(); listarProvas(); atualizarSelect() }
window.limparProva = function () { editandoProva = null;["nomeProva", "descricaoProva", "dataInicio", "dataFim"].forEach(id => document.getElementById(id).value = ""); document.getElementById("tempo").value = 60; document.getElementById("notaMinima").value = 6; document.getElementById("maxTentativas").value = 1; document.getElementById("tituloProvaProfessor").textContent = "📝 Criar Avaliação"; aplicarSegurancaForm(segurancaPadrao()) }
window.provasDoUsuario = function () { return!usuarioLogado? [] : (usuarioLogado.tipo === "master"? provas : provas.filter(p => p.professorId === usuarioLogado.id)) }
window.listarProvas = function () { const d = document.getElementById("listaProfessor"), l = provasDoUsuario(); d.innerHTML = ""; if (!l.length) { d.innerHTML = "<p>Nenhuma avaliação</p>"; return } l.forEach(p => { const idx = provas.indexOf(p), mt = p.maxTentativas || 1; d.innerHTML += `<div class="prova"><h3>📝 ${escapeHTML(p.nome)}</h3><p>❓ ${p.questoes.length} | ⏱️ ${p.tempo} min | 🔁 ${mt}x</p><p>🔑 <span class="codigo-avaliacao">${escapeHTML(p.codigo)}</span></p><p>Status: <span class="status ${p.liberada? "liberada" : "bloqueada"}">${p.liberada? "LIBERADA" : "BLOQUEADA"}</span></p><div class="acoes"><button class="${p.liberada? "btn-danger" : "btn-success"}" onclick="alternarProva(${idx})">${p.liberada? "🔒 Bloquear" : "🔓 Liberar"}</button><button class="btn-edit" onclick="editarProva(${p.id})">✏️ Editar</button><button class="btn-danger" onclick="excluirProva(${idx})">🗑️ Excluir</button></div></div>` }) }
window.editarProva = function (id) { const p = provas.find(x => x.id === id); if (!p) return; editandoProva = id; document.getElementById("nomeProva").value = p.nome; document.getElementById("descricaoProva").value = p.descricao || ""; document.getElementById("tempo").value = p.tempo; document.getElementById("notaMinima").value = p.notaMinima?? 6; document.getElementById("maxTentativas").value = p.maxTentativas || 1; document.getElementById("dataInicio").value = p.dataInicio || ""; document.getElementById("dataFim").value = p.dataFim || ""; aplicarSegurancaForm(p.seguranca); document.getElementById("tituloProvaProfessor").textContent = "✏️ Editar"; painelProfessor("provas") }
window.alternarProva = async function (i) { const p = provas[i]; if (!p) return; p.liberada =!p.liberada; salvar(); await salvarNuvem("provas", p.id, p); listarProvas() }
window.excluirProva = async function (i) { const p = provas[i]; if (!p) return; if (!confirm("Excluir '" + p.nome + "'?")) return; const id = p.id; provas.splice(i, 1); resultados = resultados.filter(r => r.provaId!== id); salvar(); await deletarNuvem("provas", id); listarProvas(); atualizarSelect(); }
window.atualizarSelect = function () { const s = document.getElementById("selectProva"); s.innerHTML = ""; const l = provasDoUsuario(); if (!l.length) { s.innerHTML = "<option value=''>Nenhuma</option>"; return } l.forEach(p => s.innerHTML += `<option value="${p.id}">${escapeHTML(p.nome)} (${p.maxTentativas || 1}x)</option>`) }
window.carregarImagem = function (e) { const a = e.target.files[0]; if (!a) return; const r = new FileReader(); r.onload = x => { imagemAtual = x.target.result; document.getElementById("imagemPreview").src = imagemAtual; document.getElementById("previewImagem").classList.remove("hidden") }; r.readAsDataURL(a) }
window.atualizarPreviewImagem = function () { const img = document.getElementById("imagemPreview"); img.style.width = (Number(document.getElementById("imagemLargura").value) || 500) + "px"; img.style.height = (Number(document.getElementById("imagemAltura").value) || 300) + "px" }
window.removerImagem = function () { imagemAtual = null; document.getElementById("previewImagem").classList.add("hidden") }
window.salvarQuestao = async function () { const pid = Number(document.getElementById("selectProva").value), en = document.getElementById("enunciado").value.trim(); const ops = ["a", "b", "c", "d"].map(id => document.getElementById(id).value.trim()), cor = document.getElementById("correta").value; if (!pid) return alert("Crie avaliação"); if (!en) return alert("Enunciado"); if (ops.some(x =>!x)) return alert("Alternativas"); if (cor === "") return alert("Correta"); const p = provas.find(x => x.id === pid); const q = { id: editando!== null? editando : Date.now(), enunciado: en, opcoes: ops, correta: Number(cor), imagem: imagemAtual, imagemLargura: Number(document.getElementById("imagemLargura").value) || 500, imagemAltura: Number(document.getElementById("imagemAltura").value) || 300 }; if (editando!== null) { const i = p.questoes.findIndex(x => x.id === editando); if (i >= 0) p.questoes[i] = q } else p.questoes.push(q); salvar(); await salvarNuvem("provas", p.id, p); limparQuestao(); listarQuestoes(); alert("✅ Salva na nuvem") }
window.limparQuestao = function () { editando = null; imagemAtual = null; document.getElementById("enunciado").value = "";["a", "b", "c", "d"].forEach(id => document.getElementById(id).value = ""); document.getElementById("correta").value = ""; document.getElementById("previewImagem").classList.add("hidden") }
window.listarQuestoes = function () { const d = document.getElementById("listaQuestoes"); d.innerHTML = ""; provasDoUsuario().forEach(p => p.questoes.forEach((q, i) => { let h = `<div class="questao"><h3>${escapeHTML(p.nome)} — Q${i + 1}</h3><p>${escapeHTML(q.enunciado)}</p>`; if (q.imagem) h += `<img src="${q.imagem}" style="width:200px"><br>`; q.opcoes.forEach((o, j) => h += `<div class="alternativa ${j === q.correta? "alternativa-correta" : ""}"><label><input type="radio" disabled><span><strong>${String.fromCharCode(65 + j)})</strong> ${escapeHTML(o)} ${j === q.correta? "✅" : ""}</span></label></div>`); h += `<button class="btn-edit btn-sm" onclick="editarQuestao(${p.id},${q.id})">✏️ Editar</button> <button class="btn-danger btn-sm" onclick="excluirQuestao(${p.id},${q.id})">🗑️ Excluir</button></div>`; d.innerHTML += h })) }
window.editarQuestao = function (pid, qid) { const p = provas.find(x => x.id === pid), q = p?.questoes.find(x => x.id === qid); if (!q) return; editando = qid; document.getElementById("selectProva").value = pid; document.getElementById("enunciado").value = q.enunciado; q.opcoes.forEach((o, i) => document.getElementById(["a", "b", "c", "d"][i]).value = o); document.getElementById("correta").value = q.correta; imagemAtual = q.imagem || null; if (imagemAtual) document.getElementById("previewImagem").classList.remove("hidden"); painelProfessor("questoes") }
window.excluirQuestao = async function (pid, qid) { const p = provas.find(x => x.id === pid); if (!p ||!confirm("Excluir questão?")) return; p.questoes = p.questoes.filter(q => q.id!== qid); salvar(); await salvarNuvem("provas", p.id, p); listarQuestoes() }
window.resultadosDoUsuario = function () { return!usuarioLogado? [] : (usuarioLogado.tipo === "master"? resultados : resultados.filter(r => r.professorId === usuarioLogado.id)) }
window.listarResultados = function () { const d = document.getElementById("resultados"), lista = resultadosDoUsuario(); if (!lista.length) { d.innerHTML = "<p>Nenhum resultado</p>"; return } let h = `<div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px"><button class="btn-success btn-sm" onclick="exportarResultadosExcel()">📥 Baixar em Excel</button><span style="font-size:12px;color:#2563eb">☁️ ${lista.length} avaliações na nuvem</span></div><div class="table-container"><table><tr><th>Aluno</th><th>Usuário</th><th>Prova</th><th>Nota</th><th>Tentativa</th><th>Data</th><th>Ações</th></tr>`; lista.slice().reverse().forEach(r => { const idx = resultados.indexOf(r); h += `<tr><td>${escapeHTML(r.aluno)}</td><td>${escapeHTML(r.usuario)}</td><td>${escapeHTML(r.prova)}</td><td>${r.nota}</td><td>${r.tentativas || 1}</td><td>${r.data}</td><td><button class="btn-danger btn-sm" onclick="excluirResultado(${idx})">🗑️</button></td></tr>` }); h += `</table></div>`; d.innerHTML = h }
window.excluirResultado = async function (i) { const r = resultados[i]; if (!r ||!confirm("Excluir " + r.aluno + "?")) return; resultados.splice(i, 1); salvar(); await deletarNuvem("avaliacoes", r.id); listarResultados() }
window.exportarResultadosExcel = function () { const lista = resultadosDoUsuario(); if (!lista.length) return alert("Nenhum"); let csv = "Aluno;Usuario;Prova;Nota;Acertos;Total;Data\n"; lista.forEach(r => { const linha = [r.aluno, r.usuario, r.prova, String(r.nota).replace(".", ","), r.acertos, r.total, r.data].map(v => `"${String(v || "").replace(/"/g, '""')}"`).join(";"); csv += linha + "\n" }); const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "avaliacoes_testeapi.csv"; a.click(); URL.revokeObjectURL(url) }
window.alterarBloqueioAluno = async function (id) { const a = alunos.find(x => x.id === id); if (!a) return; a.bloqueado =!a.bloqueado; salvarAlunos(); salvar(); await salvarNuvem("alunos", a.id, a); listarAlunosMaster(); }
window.alterarBloqueioProfessor = async function (id) { const p = usuarios.find(u => u.id === id); if (!p) return; if (p.tipo === "master") return alert("Não pode bloquear Master"); p.bloqueado =!p.bloqueado; salvarUsuarios(); salvar(); await salvarNuvem("professores", p.id, p); listarProfessores(); }
window.cadastrarAlunoMaster = async function () { if (usuarioLogado?.tipo!== "master") return alert("Somente Master"); const nome = document.getElementById("novoAlunoNome").value.trim(), usuario = document.getElementById("novoAlunoUsuario").value.trim().toLowerCase().replace(/\s+/g, ""), senha = document.getElementById("novoAlunoSenha").value; if (!nome || nome.length < 3) return alert("Nome"); if (!usuario || usuario.length < 3) return alert("Usuário min 3"); if (!senha || senha.length < 4) return alert("Senha min 4"); if (alunos.some(a => a.usuario.toLowerCase() === usuario)) return alert("Usuário já existe"); if (usuarios.some(u => u.usuario.toLowerCase() === usuario)) return alert("Já existe como professor"); const novo = { id: "aluno-" + Date.now(), nome, usuario, senha, bloqueado: false, dataCadastro: new Date().toLocaleString("pt-BR") }; alunos.push(novo); salvarAlunos(); await salvarNuvem("alunos", novo.id, novo); document.getElementById("novoAlunoNome").value = ""; document.getElementById("novoAlunoUsuario").value = ""; document.getElementById("novoAlunoSenha").value = ""; listarAlunosMaster(); alert("✅ Aluno cadastrado na nuvem testeapi-1ad07") }
window.listarAlunosMaster = function () { const div = document.getElementById("listaAlunosMaster"); const busca = (document.getElementById("buscaAluno")?.value || "").toLowerCase(); let lista = alunos; if (busca) lista = alunos.filter(a => a.nome.toLowerCase().includes(busca) || a.usuario.toLowerCase().includes(busca)); if (!lista.length) { div.innerHTML = "<p>Nenhum aluno</p>"; return } let h = `<div class="table-container"><table><tr><th>Nome</th><th>Usuário</th><th>Status</th><th>Data</th><th>Ações</th></tr>`; lista.slice().reverse().forEach(a => { const status = a.bloqueado? '<span class="bloqueado">🔒 BLOQUEADO</span>' : '<span class="liberado">✅ Ativo</span>'; h += `<tr><td>${escapeHTML(a.nome)}</td><td>${escapeHTML(a.usuario)}</td><td>${status}</td><td>${escapeHTML(a.dataCadastro || "")}</td><td><div style="display:flex;gap:4px;flex-wrap:wrap"><button class="btn-edit btn-sm" onclick="alterarSenhaAluno('${a.id}')">🔑</button><button class="${a.bloqueado? 'btn-unblock btn-sm' : 'btn-block btn-sm'}" onclick="alterarBloqueioAluno('${a.id}')">${a.bloqueado? '🔓' : '🔒'}</button><button class="btn-danger btn-sm" onclick="excluirAlunoMaster('${a.id}')">🗑️</button></div></td></tr>`; }); h += `</table></div><p>Total: ${lista.length}</p>`; div.innerHTML = h; }
window.alterarSenhaAluno = async function (id) { if (usuarioLogado?.tipo!== "master") return; const a = alunos.find(x => x.id === id); if (!a) return; const nova = prompt("Nova senha para " + a.nome + ":"); if (nova === null) return; if (nova.length < 4) return alert("Min 4"); a.senha = nova; salvarAlunos(); await salvarNuvem("alunos", a.id, a); listarAlunosMaster(); alert("✅ Senha alterada") }
window.excluirAlunoMaster = async function (id) { if (usuarioLogado?.tipo!== "master") return; const a = alunos.find(x => x.id === id); if (!a) return; if (!confirm("Excluir " + a.nome + "?")) return; alunos = alunos.filter(x => x.id!== id); resultados = resultados.filter(r => r.usuario!== a.usuario); salvarAlunos(); salvar(); await deletarNuvem("alunos", id); listarAlunosMaster(); }
window.exportarAlunosExcel = function () { if (!alunos.length) return alert("Nenhum aluno"); let csv = "Nome;Usuario;Senha;Bloqueado;DataCadastro\n"; alunos.forEach(a => { const linha = [a.nome, a.usuario, a.senha, a.bloqueado? "SIM" : "NAO", a.dataCadastro || ""].map(v => `"${String(v || "").replace(/"/g, '""')}"`).join(";"); csv += linha + "\n" }); const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" }); const url = URL.createObjectURL(blob); const al = document.createElement("a"); al.href = url; al.download = "alunos_testeapi.csv"; al.click(); URL.revokeObjectURL(url) }
window.cadastrarProfessor = async function () { if (usuarioLogado?.tipo!== "master") return; const n = document.getElementById("novoProfessorNome").value.trim(), u = document.getElementById("novoProfessorUsuario").value.trim().toLowerCase().replace(/\s+/g, ""), s = document.getElementById("novoProfessorSenha").value; if (!n ||!u || s.length < 4) return alert("Dados inválidos"); if (usuarios.some(x => x.usuario.toLowerCase() === u) || alunos.some(x => x.usuario.toLowerCase() === u)) return alert("Usuário existe"); const novo = { id: "prof-" + Date.now(), nome: n, usuario: u, senha: s, tipo: "professor", bloqueado: false }; usuarios.push(novo); salvarUsuarios(); await salvarNuvem("professores", novo.id, novo); listarProfessores(); document.getElementById("novoProfessorNome").value = ""; document.getElementById("novoProfessorUsuario").value = ""; document.getElementById("novoProfessorSenha").value = ""; alert("✅ Cadastrado na nuvem") }
window.listarProfessores = function () { const ps = usuarios.filter(u => u.tipo === "professor"), d = document.getElementById("listaProfessores"); if (!ps.length) { d.innerHTML = "<p>Nenhum</p>"; return } d.innerHTML = `<div class="table-container"><table><tr><th>Nome</th><th>Usuário</th><th>Status</th><th>Ações</th></tr>${ps.map(p => { const status = p.bloqueado? '<span class="bloqueado">🔒 BLOQUEADO</span>' : '<span class="liberado">✅ Ativo</span>'; return `<tr><td>${escapeHTML(p.nome)}</td><td>${escapeHTML(p.usuario)}</td><td>${status}</td><td><div style="display:flex;gap:4px;flex-wrap:wrap"><button class="btn-edit btn-sm" onclick="alterarSenhaProfessor('${p.id}')">🔑</button><button class="${p.bloqueado? 'btn-unblock btn-sm' : 'btn-block btn-sm'}" onclick="alterarBloqueioProfessor('${p.id}')">${p.bloqueado? '🔓' : '🔒'}</button><button class="btn-danger btn-sm" onclick="excluirProfessor('${p.id}')">🗑️</button></div></td></tr>` }).join("")}</table></div>`; }
window.alterarSenhaProfessor = async function (id) { const p = usuarios.find(u => u.id === id); const n = prompt("Nova senha:"); if (n && n.length >= 4) { p.senha = n; salvarUsuarios(); await salvarNuvem("professores", p.id, p); alert("Alterada") } }
window.excluirProfessor = async function (id) { if (!confirm("Excluir professor?")) return; usuarios = usuarios.filter(u => u.id!== id); salvarUsuarios(); await deletarNuvem("professores", id); listarProfessores() }
window.alterarMinhaSenha = async function () { const a = document.getElementById("senhaAtual").value, n = document.getElementById("novaSenha").value, c = document.getElementById("confirmarSenha").value; if (a!== usuarioLogado.senha) return alert("Senha atual errada"); if (n.length < 4) return alert("Min 4"); if (n!== c) return alert("Não confere"); usuarioLogado.senha = n; const b = usuarios.find(u => u.id === usuarioLogado.id); if (b) b.senha = n; salvarUsuarios(); await salvarNuvem("professores", b.id, b); alert("Alterada na nuvem") }
window.logBanco = function (msg) { const d = document.getElementById("logBanco"); if (d) d.innerHTML = new Date().toLocaleTimeString() + " - " + msg + "<br>" + d.innerHTML; }
window.limparTodasProvas = async function () { if (usuarioLogado?.tipo!== "master") return alert("Só Master!"); if (!confirm("APAGAR TODAS AS PROVAS da nuvem?")) return; if (!confirm("TEM CERTEZA?")) return; logBanco("Apagando provas..."); const snap = await getDocs(collection(db, "provas")); for (const d of snap.docs) await deleteDoc(doc(db, "provas", d.id)); provas = []; salvar(); listarProvas(); atualizarSelect(); logBanco("✅ " + snap.size + " provas apagadas"); alert("✅ Apagadas!") }
window.limparQuestoesTodas = async function () { if (!confirm("Apagar todas QUESTÕES?")) return; for (let p of provas) { p.questoes = []; await salvarNuvem("provas", p.id, p); } salvar(); logBanco("✅ Questões zeradas"); alert("✅ Questões apagadas!") }
window.limparTodosResultados = async function () { if (!confirm("APAGAR TODAS NOTAS?")) return; const snap = await getDocs(collection(db, "avaliacoes")); for (const d of snap.docs) await deleteDoc(doc(db, "avaliacoes", d.id)); resultados = []; salvar(); logBanco("✅ " + snap.size + " notas apagadas"); alert("✅ Notas apagadas!"); listarResultados(); }
window.limparResultadosProva = async function () { const codigo = prompt("Código da prova:"); if (!codigo) return; const p = provas.find(x => x.codigo === codigo.toUpperCase()); if (!p) return alert("Código não encontrado"); if (!confirm(`Apagar notas da prova ${p.nome}?`)) return; const snap = await getDocs(collection(db, "avaliacoes")); let c = 0; for (const d of snap.docs) { if (d.data().provaId === p.id) { await deleteDoc(doc(db, "avaliacoes", d.id)); c++; } } resultados = resultados.filter(r => r.provaId!== p.id); salvar(); logBanco(`✅ ${c} notas apagadas`); alert(`✅ ${c} notas apagadas`); listarResultados(); }
window.resetarSenhasAlunos = async function () { const nova = document.getElementById("senhaPadraoReset").value || "1234"; if (!confirm(`Resetar senhas alunos para "${nova}"?`)) return; for (let a of alunos) { a.senha = nova; await salvarNuvem("alunos", a.id, a); } salvarAlunos(); logBanco(`✅ ${alunos.length} senhas resetadas`); alert("✅ Resetadas!"); listarAlunosMaster(); }
window.resetarSenhasProfessores = async function () { const nova = document.getElementById("senhaPadraoReset").value || "1234"; if (!confirm(`Resetar senhas professores para "${nova}"?`)) return; let c = 0; for (let u of usuarios) { if (u.tipo === "professor") { u.senha = nova; await salvarNuvem("professores", u.id, u); c++; } } salvarUsuarios(); logBanco(`✅ ${c} senhas resetadas`); alert("✅ Resetadas!"); listarProfessores(); }
window.zerarBancoCompleto = async function () { if (!confirm("☢️ ZERAR TUDO? Provas + Notas")) return; const conf = prompt('Digite "ZERAR":'); if (conf!== "ZERAR") return; logBanco("☢️ ZERANDO..."); const snapP = await getDocs(collection(db, "provas")); for (const d of snapP.docs) await deleteDoc(doc(db, "provas", d.id)); const snapR = await getDocs(collection(db, "avaliacoes")); for (const d of snapR.docs) await deleteDoc(doc(db, "avaliacoes", d.id)); provas = []; resultados = []; salvar(); logBanco("☢️ BANCO ZERADO!"); alert("☢️ Banco zerado"); }
aplicarSegurancaForm(segurancaPadrao()); mostrar("inicio");
